jobs:
- job: osx
  pool:
    vmImage: macOS-10.15
  strategy:
    matrix:
      osx_64_:
        CONFIG: osx_64_
        UPLOAD_PACKAGES: 'True'
  timeoutInMinutes: 360
  steps:
  - task: Maven@3
    inputs:
      goals:
        - package

