jobs:
- job: osx
  pool:
    vmImage: macOS-10.15
  strategy:
    matrix:
      osx_64_:
        CONFIG: osx_64_
        UPLOAD_PACKAGES: 'True'
  timeoutInMinutes: 360
  steps:
  # TODO: Fast finish on azure pipelines?
  - script: |
      mvn clean package
    displayName: Run OSX build

